### ISSUE TITLE
Conflicts with FIRST vue @ attribute / plugin does not work at all

### ISSUE THREAD

**Issue by remixer-dec** [lxs24sxl/vite-plugin-html-env#14]
```<section @scroll.passive="loadOnScroll"></section>```
gives an error Cannot be closed: section,  
but  
```<section class="asdf" @scroll.passive="loadOnScroll"></section>```
works fine  (no errors)
  
also using default prefix/suffix i got an error ```Unable to parse HTML; Illegal tag name. Use '&lt;' to print '<'.```
and changing suffix/prefix to [[ / ]] removes the first part of HTML content and places nothing in the place of environment variable
I tried variables from process.env with prefix option in config AND .env file, tried different prefixes/suffixes, no effect

**Comment by remixer-dec** [comment]
Alright, finally got it to work
1) why does it parse .env from src directory and not from the project's root???
2) I guess you CANNOT use ANY REGEXP-SYNTAX CHARACTER in prefix and suffix (default preffix and suffix still does not work at all)

**Comment by lxs24sxl** [comment]
Thanks for your feedback

v1.2.3 
Available in REGEXP-SYNTAX CHARACTER prefix and suffix.
`Cannot be closed: secion` This problem has also been solved


1. The read location of the env file will change depending on the root and envDir configuration.
2. Vite exposes environment variables on a special `import.meta.env` object.

**Comment by remixer-dec** [comment]
Hello, thanks for quick fixes. Just tested 1.2.3.
the @ is indeed fixed
regexp-prefix/suffix: {{ / }} do work, [[ / ]] does not work
default prefix/suffix: 
Unable to parse HTML; Illegal tag name. Use '&lt;' to print '<'.
 at {"file":"/index.html","line":80,"column":37}
>    at handleParseError (.../node_modules/vite/dist/node/chunks/dep-561c5231.js:41084:11)
>     at traverseHtml (.../node_modules/vite/dist/node/chunks/dep-561c5231.js:41040:9)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async devHtmlHook (.../node_modules/vite/dist/node/chunks/dep-561c5231.js:57456:5)
>     at async applyHtmlTransforms (.../node_modules/vite/dist/node/chunks/dep-561c5231.js:41483:21)
>     at async viteIndexHtmlMiddleware (.../node_modules/vite/dist/node/chunks/dep-561c5231.js:57526:28

variables exported with `export VITE_TEST_VAR=123` command do not appear after running npx vite build, not sure how import.meta.env can help  
for now, i made a non-flexible [microplugin](https://github.com/remixer-dec/rg-backup/blob/2c1d9d19eb28a9f254f72ae423f3ef5678f734d6/vite-plugins.js#L127) for my specific case, but I wish you the best of luck on development of this project!

**Comment by lxs24sxl** [comment]
This warning looks to be output by `vite`. Can you provide a snippet of the `index.html` file code? Maybe I can find a compatible solution.

**Comment by remixer-dec** [comment]
```html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
  <div><{ VITE_TEST }></div>
</body>
</html>

```

**Comment by lxs24sxl** [comment]
This warning is really output by vite.

You can use another replacement rule.

```html
<!DOCTYPE html>
<html>
<head>

</head>
<body>
  <div>import.meta.env.VITE_TEST</div>
</body>
</html>
```
