### ISSUE TITLE
how to use if conditional

### ISSUE THREAD

**Issue by paper-florent** [lxs24sxl/vite-plugin-html-env#9]
Hello first thank you for your work !

Have a question. How do you actually add a condition rendering ?

```
<{ if(MODE !== 'development'){  }>
```

Do you know how I can achieve that ?

Thank you a lot

**Comment by lxs24sxl** [comment]
In general, environment variables are fixed values, so you can create different .env files to distinguish between environments.


.env  (loaded in all cases)
```
VITE_APP_PRODUCTION_SOURCE_MAP=1
```

.env.development (only loaded in specified mode)
```
VITE_APP_PRODUCTION_SOURCE_MAP=0
```

**Comment by paper-florent** [comment]
I did a bit differently by adding a plugin. I wanted to load a script in the html base on the env. But with a plugins its working kind of the same
